### ISSUE TITLE
Minification

### ISSUE THREAD

**Issue by mustaqs** [cse110-fa22-group22/cse110-fa22-group22#49]
Look into Minification, what is required and how to do it,

**Comment by pdn002** [comment]
What is minification?
Minification is basically the process of conducing the text in JavaScript, html, CSS files. Code is restructured so that text can fit together as tightly as possible. Almost all whitespace is gotten rid of. This is done so that the program can run much quicker. If there is less white space to read then the application will run a bit faster. The downside of this is that the result code from minification is very unreadable to programmers.

How do we minify?
To minify the code we can copy and paste are code into a free online JS, html, and CSS minifier. Since the text becomes very unreadable it is best to keep two different directories of files. One directory is for the human readable file that will be modified like normal. The other directory will contain the minified version of the code. The application should be deployed from the minified directory. Anytime there are changes in the readable directory those changes should be be copied and minified into minify directory.

When will we minify?
Once basically all the code for this CRUD application is done, we will copy all the files into a minify directory, minify the code, then deploy the website from that directory. This will lessen the amount of times we need to minify our code.

**Comment by varunraisinghal** [comment]
Finished within the branch that deals with Phase 2 of pipelines
